- hosts: localhost
  gather_facts: no
  vars_files:
          - awspass.yml
  tasks:
  - name: Launching ec2 Instance
    ec2:
      key_name: "awskey"
      instance_type: "t2.micro"
      image: "ami-0a780d5bac870126a"
      wait: "yes"
      count: 1
      vpc_subnet_id: "subnet-75173637"
      assign_public_ip: yes
      region: "ap-south-1"
      state: present
      group_id: "sg-02d55736377gedbsbd"
      aws_access_key: "{{ myuser }}"
      aws_secret_key: "{{ mypass }}"
    register: ec2
  - debug:
      var: ec2.instances[0].public_ip
  - name: Hostgroup
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: ec2_login
    with_items: "{{ ec2.instances }}"
  - name: Configure SSH
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"

  - name: Launch ec2 Instance
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"
- hosts: ec2_login
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Configur httpd
    package:
      name: httpd
      state: present
  - name: Starting httpd Services
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Copying Webpages to /var/www/html
    copy:
      src: "/ansible_task/index.html"
      dest: "/var/www/html"

